addons:
  postgresql: 9.6
before_script:
  - psql -c 'create database home_test;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.6.4
script:
  - bundle exec rails db:migrate
  - bundle exec rspec
services:
  - redis-server
env:
  global:
    - RAILS_ENV=env