addons:
  postgresql: 9.6.16
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database home_test;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.6.4
script:
  - bundle exec rails db:migrate
  - bundle exec rspec
services:
  - redis-server
env:
  global:
    - RAILS_ENV=test