version: '3'
services:
  home:
    container_name: app
    build: .
#    command: bash -c "rm -f ./tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "while [ true ]; do sleep 10; done"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - elasticsearch
      - redis
    environment:
      - RAILS_ENV=development
      - AUTH_URL=http://host.docker.internal:4000
      - KAFKA_URL=kafka://host.docker.internal:9092
      - DATABASE_URL=postgres
    links:
      - postgres

  postgres:
    container_name: home_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres
    volumes:
    - ./tmp/db:/var/lib/postgresql/data

  elasticsearch:
    container_name: home_elasticsearch
    image: elasticsearch:7.4.0
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200"

  redis:
    container_name: home_redis
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
