version: "3"
services:
  homebackend:
    container_name: homebackend
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    volumes:
      - ".:/home_back"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
