version: '3'
services:
  home:
    container_name: app
    build: .
#    command: bash -c "rm -f ./tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "while [ true ]; do sleep 10; done"
#    command: sidekiq
    volumes:
      - .:/app
    ports:
      - "3002:3000"
    expose:
      - 3001
    depends_on:
      - postgres
      - elasticsearch
      - redis
    environment:
      - RAILS_ENV=development
      - AUTH_URL=http://host.docker.internal:4000
      - KAFKA_URL=kafka://host.docker.internal:9092
      - DATABASE_URL=postgres
      - REDIS_URL=redis://redis:6379
      - FCM_AUTH_KEY=AAAAimsF8i4:APA91bEVoYjiN4vcJfNLi8tg5iF2_CEbiri1q-EmoeoyhkHKVFLZ7TXVUFd5XkNBu6np0eK78cX8WjOEXB-DJYxOpjdA98J4RqLK76oJXFLTnggrQaMbQZRQMGacB1MAGNeLUrp1cMu0
    links:
      - postgres
      - elasticsearch
      - redis

  postgres:
    container_name: home_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres
#    volumes:
#    - ./tmp/db:/var/lib/postgresql/data

  elasticsearch:
    container_name: home_elasticsearch
    image: elasticsearch:7.4.0

  redis:
    container_name: home_redis
    image: redis
    command: redis-server
