version: '3'
services:
  home_financial:
    container_name: home_financial
    build: .
    command: bash -c "rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/financial
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - RAILS_ENV=development
    links:
      - postgres
  postgres:
    container_name: home_financial_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres
    volumes:
    - ./tmp/db:/var/lib/postgresql/data
